// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/Auth/AuthProvider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Qualiphy stylesheet */}
        <link 
          rel="stylesheet" 
          href="https://firebasestorage.googleapis.com/v0/b/qualiphy-web-d918b.appspot.com/o/style-v4.css?alt=media&token=34735782-16e8-4a2f-9eaa-426d65af48b2" 
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} bg-[#F7F7F7] antialiased`}>
        <AuthProvider>
          {children}
        </AuthProvider>

        {/* Qualiphy Scripts - Load them at the end of body */}
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" strategy="afterInteractive" />
        <Script
          id="qualiphy-script"
          src="https://www.app.qualiphy.me/scripts/quidget_disclosure.js"
          data-formsrc="https://www.app.qualiphy.me/qualiphy-widget?clinic=Lily's&clinicId=2936&first_name=&last_name=&email=&phone_number=&gender=&exams=selectable&tele_state_required=true&token=03c1104d9f29a55f0355920b6dee309f3c46222f"
          data-timezone="-5"
          data-examhours="[{&quot;SUN&quot;:{&quot;FROM&quot;:&quot;00:00&quot;,&quot;TO&quot;:&quot;23:59&quot;,&quot;isDaySelected&quot;:true}},{&quot;MON&quot;:{&quot;FROM&quot;:&quot;00:00&quot;,&quot;TO&quot;:&quot;23:59&quot;,&quot;isDaySelected&quot;:true}},{&quot;TUE&quot;:{&quot;FROM&quot;:&quot;00:00&quot;,&quot;TO&quot;:&quot;23:59&quot;,&quot;isDaySelected&quot;:true}},{&quot;WED&quot;:{&quot;FROM&quot;:&quot;00:00&quot;,&quot;TO&quot;:&quot;23:59&quot;,&quot;isDaySelected&quot;:true}},{&quot;THU&quot;:{&quot;FROM&quot;:&quot;00:00&quot;,&quot;TO&quot;:&quot;23:59&quot;,&quot;isDaySelected&quot;:true}},{&quot;FRI&quot;:{&quot;FROM&quot;:&quot;00:00&quot;,&quot;TO&quot;:&quot;23:59&quot;,&quot;isDaySelected&quot;:true}},{&quot;SAT&quot;:{&quot;FROM&quot;:&quot;00:00&quot;,&quot;TO&quot;:&quot;23:59&quot;,&quot;isDaySelected&quot;:true}}]"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}

// Add TypeScript interface for the window object to include showDisclosureModal
declare global {
  interface Window {
    showDisclosureModal: () => void;
  }
}